### ISSUE TITLE
Enable Release Drafter if needed

### ISSUE THREAD

**Issue by basil** [openrewrite/rewrite-jenkins#21]
If a plugin is using automated release, then any Release Drafter configuration should be _deleted_ as explained [here](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#configure-release-drafter). But if the plugin is _not_ using automated release and missing a Release Drafter configuration, it should be _added_ to `.github/release-drafter.yml` and `.github/workflows/release-drafter.yml` as per the archetype:

- https://github.com/jenkinsci/archetypes/blob/7a9f24981d3c1993e47e540bb26d21f1f4469ce7/common-files/.github/release-drafter.yml
- https://github.com/jenkinsci/archetypes/blob/7a9f24981d3c1993e47e540bb26d21f1f4469ce7/common-files/.github/workflows/release-drafter.yml

The above configuration is for plugins with two digits in their version number. For plugins with three digits (SemVer-style), the following configuration should be used instead:

```yml
_extends: .github
name-template: $NEXT_PATCH_VERSION
tag-template: ${artifactId}-$NEXT_PATCH_VERSION
version-template: $MAJOR.$MINOR.$PATCH
```
