### ISSUE TITLE
Translate existing refactoring rules from Jackpot

### ISSUE THREAD

**Issue by jglick** [openrewrite/rewrite-jenkins#6]
Jenkins core already contains some [Jackpot](https://netbeans.apache.org/jackpot/index.html)-based rules in the [`META-INF/upgrade` pseudo-package](https://github.com/jenkinsci/jenkins/tree/05a0cf3ffa90abfec417553341424de08661e7a5/core/src/main/resources/META-INF/upgrade). These are offered automatically to plugin developers using the NetBeans IDE. It would be better to delete that and create analogous rules in this repo that anyone could use.

**Comment by timtebeek** [comment]
Thanks for chiming in here @jglick !

### Refaster recipes
I've had a quick look at the .hint files in Jenkins, and it appears to me like quite a few of those would be a candidate for our simplified recipe definitions using the Refaster annotations. See for example [UseStringIsEmpty.java](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/lang/UseStringIsEmpty.java):

```java
import com.google.errorprone.refaster.annotation.AfterTemplate;
import com.google.errorprone.refaster.annotation.BeforeTemplate;

public class UseStringIsEmpty {
    @BeforeTemplate
    boolean before(String s) {
        return s.length() > 0;
    }

    @AfterTemplate
    boolean after(String s) {
        return !s.isEmpty();
    }
}
```

We allow you to write tests for such recipes as well, as seen in [UseStringIsEmptyTest.java](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/test/java/org/openrewrite/java/migrate/lang/UseStringIsEmptyTest.java#L38-L49)
```java
    @Test
    void lengthGreaterZero() {
        rewriteRun(
          java( // before
            """
              class Test {
                  void m(String s) {
                      boolean b = s.length() > 0;
                  }
              }
              """, // after
            """
              class Test {
                  void m(String s) {
                      boolean b = !s.isEmpty();
                  }
              }
              """
          )
        );
    }
```

I don't think it requires a lot of creativity to see how that could serve to similarly convert for instance the use of `printStackTrace` in [META-INF/upgrade/Functions.hint](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/META-INF/upgrade/Functions.hint)

### Declarative recipes
Other simpler one to one replacements can be achieved with a [declarative yaml recipe](https://docs.openrewrite.org/reference/yaml-format-reference) only, such that you can achieve these replacements with three lines of yaml; for instance for [META-INF/upgrade/JSR-305.hint](https://github.com/jenkinsci/jenkins/blob/05a0cf3ffa90abfec417553341424de08661e7a5/core/src/main/resources/META-INF/upgrade/JSR-305.hint)
```hint
javax.annotation.CheckForNull => edu.umd.cs.findbugs.annotations.CheckForNull;;
javax.annotation.Nonnull => edu.umd.cs.findbugs.annotations.NonNull;;
javax.annotation.Nullable => edu.umd.cs.findbugs.annotations.Nullable;;
```
In this case, the [change type recipe](https://docs.openrewrite.org/recipes/java/changetype) is likely what you need.
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.ChangeTypeExample
displayName: Change type example
recipeList:
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: javax.annotation.CheckForNull
      newFullyQualifiedTypeName: edu.umd.cs.findbugs.annotations.CheckForNull
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: javax.annotation.Nonnull
      newFullyQualifiedTypeName: edu.umd.cs.findbugs.annotations.NonNull
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: javax.annotation.Nullable
      newFullyQualifiedTypeName: edu.umd.cs.findbugs.annotations.Nullable
```

Hope that helps get you started! If you have any questions feel free to chime in here or on [our public Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA).
